name: Update Data
run-name: Update Data
on: [workflow_dispatch]
jobs:
  Update-Data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: ls ${{ github.workspace }}
      - name: Update data
        run: ./gradlew updateData
      - run: ls ${{ github.workspace }}
      - run: git status
      - name: Commit new data
        uses: EndBug/add-and-commit@v9
        with:
          message: update data (github actions)
